### ISSUE TITLE
Rename properties: `idfa` -> `advertisingId`, `idfv` -> `developerScopedId`

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/TrackHAR#21]
Currently, we're using `idfa` for the Apple IDFA and Google Advertising ID, and `ifdv` for Apple's IDFV.

In Android 12, Google has introduced a new *App set ID* (ASID), which is essentially equivalent to the IDFV:

* https://developer.android.com/training/articles/app-set-id
* https://developers.google.com/android/reference/com/google/android/gms/appset/AppSetIdInfo

I've already seen this (https://support.singular.net/hc/en-us/articles/360037640812-Server-to-Server-S2S-Integration-Guide#Collecting_and_Sending_the_App_Set_ID_Required_for_Android_12) in the new singular.net adapter I'm working on (https://github.com/tweaselORG/TrackHAR/issues/16). For now, I'll mark this as `idfv` to match the previous usage.

But I propose to rename the two properties to `advertisingId` and `developerScopedId`. While that would unfortunately be a breaking change, I think it makes sense and should be less confusing.

**Comment by baltpeter** [comment]
I will also list the `ANDROID_ID` under `idfv`/`developerScopedId`. According to https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID:

> On Android 8.0 (API level 26) and higher versions of the platform, a 64-bit number (expressed as a hexadecimal string), unique to each combination of app-signing key, user, and device.

Previously, this would have rather fit under `idfa` but I think Android 8 is old enough for us to not consider it relevant anymore:

> In versions of the platform lower than Android 8.0 (API level 26), a 64-bit number (expressed as a hexadecimal string) that is randomly generated when the user first sets up the device and should remain constant for the lifetime of the user's device.

**Comment by baltpeter** [comment]
We should also update https://github.com/tweaselORG/tracker-wiki/blob/adee1c563e572787ee7ce26f5ce82c321fb58ad2/i18n/en.json#L97-L98 to include `(GAID, or IDFA)` and `(IDFA, ASID, or ANDROID_ID)`.

And it might be good to also add docstrings in `index.ts`, even though I don't think Typedoc will include them in the rendered docs.

**Comment by baltpeter** [comment]
> We should also update [tweaselORG/tracker-wiki@`adee1c5`/i18n/en.json#L97-L98](https://github.com/tweaselORG/tracker-wiki/blob/adee1c563e572787ee7ce26f5ce82c321fb58ad2/i18n/en.json#L97-L98) to include `(GAID, or IDFA)` and `(IDFA, ASID, or ANDROID_ID)`.

I'm doing that in https://github.com/tweaselORG/tracker-wiki/pull/16.

**Comment by zner0L** [comment]
I think that makes sense. Let's do what you propose.
